### PR TITLE
Giza

### PR DESCRIPTION
**Pull request by mnaamani**
Update types and polkadot-js versions for Giza network.
Update export balances to use api.query.system.account() to enumerate all accounts and optionally cap max balance.
Note: Staked balances (in council, proposals, and working groups) I think will not be captured.
Total balance exported = free + reserved.

Drop export workers script.
Applied some prettier formatting.

eg usage for export balances

setting env `CAP_BALANCE=0` is equivalent to no capping and will return actual balance in account.
setting env `CAP_BALANCE=20000` will cap balances at 20000

### CODE REVIEW

**Comment by mnaamani** [comment]
Should we consider filtering out accounts with balance less than the existential deposit value set for Olympia runtime?

**Comment by mnaamani** [comment]
cc: @traumschule

**Comment by traumschule** [comment]
> Should we consider filtering out accounts with balance less than the existential deposit value set for Olympia runtime?

Could make sense. I found 1278 / 5627 accounts with < 10 tokens and additional 85.9 M in accounts that never transacted.

**Review by bwhm — APPROVED** [review]
:+1:

**Pull request merged**
